export const LANGUAGES = Object.freeze({
  ABYSSAL: 'abyssal',
  ANARI: 'anari',
  CELESTIAL: 'celestial',
  CENTAUR: 'centaur',
  DEEP_SPEECH: 'deep speech',
  DRACONIC: 'draconic',
  DRUIDIC: 'druidic',
  DWARVISH: 'dwarvish',
  ERSKIN: 'erskin',
  GAELING: 'gaeling',
  GASQUEN: 'gasquen',
  GHOUL: 'ghoul',
  GNOLLISH: 'gnollish',
  GOBLINISH: 'goblinish',
  HELVAENIC: 'helvaenic',
  HIGH_BOROS: 'high boros',
  HIGH_DROW: 'high drow',
  HUUN: 'huun',
  INFERNAL: 'infernal',
  JOTUN: 'jotun',
  KHEMITIAN: 'khemitian',
  KIRKUT: 'kirkut',
  KOBOLD: 'kobold',
  KRA: 'kra',
  LANGUAGES: 'languages',
  LIZARDMAN: 'lizardman',
  MEERUWHAN: 'meeruwhan',
  MERMAN: 'merman',
  NORSK: 'norsk',
  OGHAM: 'ogham',
  ORCISH: 'orcish',
  PRIMORDIAL: 'primordial',
  SEMURIC: 'semuric',
  SYLVAN: 'sylvan',
  THIEVES_CANT: "thieves' cant",
  UNDERCOMMON: 'undercommon',
  WESTERLING: 'westerling',
  XHAEN: "xha'en",
});
