MONSTER_TYPES = {
  ABERRATION: 'aberration',
  ANIMAL: 'animal',
  CELESTIAL: 'celestial',
  CONSTRUCT: 'construct',
  DEMON: 'demon',
  DEVIL: 'devil',
  DRAGON: 'dragon',
  ELEMENTAL: 'elemental',
  FEY: 'fey',
  GIANT: 'giant',
  HUMANOID: 'humanoid',
  MAGICAL_BEAST: 'magical beast',
  MONSTROUS_HUMANOID: 'monstrous humanoid',
  OOZE: 'ooze',
  PLANT: 'plant',
  UNDEAD: 'undead',
  VERMIN: 'vermin',
};
